themes:
  - name: "nordic"
    colors:
      - "#191D24"
      - "#1E222A"
      - "#222630"
      - "#242933"
      - "#2E3440"
      - "#3B4252"
      - "#434C5E"
      - "#4C566A"
      - "#60728A"
      - "#BBC3D4"
      - "#5E81AC"
      - "#81A1C1"
      - "#88C0D0"
      - "#B74E58"
      - "#CB775D"
      - "#E7C173"
      - "#97B67C"
      - "#A97EA1"
