theme = "custom"
mode = "auto"
line_numbers = false
wrap_lines = false
hunk_headers = true
menu_bar = true
agent_notes = false
copy_decorations = false
cursor_line = "row"

[custom_theme]
base = "rose-pine"
background = "#191724"
panel = "#191724"
panelAlt = "#1f1d2e"

[keybindings]
"hunk.review.previousHunk" = "ö"
"hunk.review.nextHunk" = "ä"
