import = ["~/.config/sesh/spp.toml"]

blacklist = ["^scratch$", "^_"]

[default_session]
preview_command = "eza --all --git --icons=always --group-directories-first --color=always {}"

[[wildcard]]
pattern = "~/repos/**"
startup_command = "nvim"

[[session]]
name = "dots"
path = "~/dots"
startup_command = "nvim"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"
