import = ["~/.config/sesh/spp.toml"]

blacklist = ["^scratch$", "^_"]

[[wildcard]]
pattern = "~/repos/**"
startup_command = "nvim"

[[session]]
name = "dots"
path = "~/dots"
startup_command = "nvim"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"
