#!/bin/bash

theme = nordic

adjust-cell-height = 45%
font-family = Berkeley Mono
font-size = 15

confirm-close-surface = false

cursor-style-blink = false
mouse-hide-while-typing = true

macos-option-as-alt = false
macos-titlebar-style = hidden
# window-padding-balance = true

cursor-color=cell-foreground
cursor-text=cell-background
cursor-style = block
mouse-hide-while-typing = true
shell-integration-features = no-cursor
