#!/bin/bash
# focus window
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# move window
shift + cmd - h : yabai -m window --swap west
shift + cmd - j : yabai -m window --swap south
shift + cmd - k : yabai -m window --swap north
shift + cmd - l : yabai -m window --swap east

# warp window
shift + lalt + cmd - h : yabai -m window --warp west
shift + lalt + cmd - j : yabai -m window --warp south
shift + lalt + cmd - k : yabai -m window --warp north
shift + lalt + cmd - l : yabai -m window --warp east

# resize window
ctrl + cmd - h : yabai -m window --resize right:-100:0
ctrl + cmd - j : yabai -m window --resize bottom:0:100
ctrl + cmd - k : yabai -m window --resize bottom:0:-100
ctrl + cmd - l : yabai -m window --resize right:100:0

# toggle floating
cmd + shift - space : yabai -m window --toggle float \
                      yabai -m window --grid 10:10:1:1:8:8

# Make window zoom to fullscreen
shift + cmd - f : yabai -m window --toggle zoom-fullscreen

# Equalize size of windows
ctrl + cmd - e : yabai -m space --balance

# Toggle sketchybar
shift + cmd - m : sketchybar --bar hidden=toggle

# Reload skhd config
ctrl + lalt + cmd - r : skhd --restart-service
# Reload yabai config
ctrl + cmd - r : yabai --restart-service
