return {
  {
    "rose-pine/neovim",
    lazy = false,
    name = "rose-pine",
    config = function()
      ---@diagnostic disable-next-line: missing-fields
      require("rose-pine").setup {
        styles = {
          transparency = true,
        },
        highlight_groups = {
          MatchParen = { fg = "love", bg = "love", blend = 25 },
          CursorLineNr = { fg = "gold", bold = true },
          StatusLineTerm = { fg = "subtle", bg = "none" },
          StatuslineSeparator = { fg = "overlay", bg = "none" },
          StatuslineTextMain = { fg = "text", bg = "overlay" },
          StatuslineTextBold = { link = "StatuslineTextMain", bg = "overlay", bold = true },
          StatuslineTextAccent = { fg = "muted", bg = "overlay" },
          StatuslineModeCommand = { fg = "love", bg = "overlay", bold = true },
          StatuslineModeInsert = { fg = "foam", bg = "overlay", bold = true },
          StatuslineModeNormal = { fg = "rose", bg = "overlay", bold = true },
          StatuslineModeOther = { fg = "rose", bg = "overlay", bold = true },
          StatuslineModeReplace = { fg = "pine", bg = "overlay", bold = true },
          StatuslineModeVisual = { fg = "iris", bg = "overlay", bold = true },
          StatuslineNotSaved = { fg = "gold", bg = "overlay" },
          StatuslineReadOnly = { fg = "love", bg = "overlay" },
          StatuslineLspOn = { fg = "pine", bg = "overlay" },
          StatuslineFormatterStatus = { fg = "foam", bg = "overlay" },
          StatuslineCopilot = { fg = "rose", bg = "overlay" },
          QuickFixFilename = { fg = "text" },
          NoiceCmdlinePopupBorder = { fg = "rose" },
          NoiceCmdlinePopupTitle = { link = "NoiceCmdlinePopupBorder" },
          NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
          NoiceMini = { fg = "muted" },
          CodeCompanionChatHeader = { fg = "rose" },
          CodeCompanionChatSeparator = { fg = "muted" },
          CodeCompanionChatTokens = { fg = "gold" },
          CodeCompanionChatTool = { fg = "pine" },
          CodeCompanionChatVariable = { fg = "base", bg = "iris" },
          CodeCompanionVirtualText = { fg = "iris" },
          DapUIStepOver = { fg = "foam" },
          DapUIStepInto = { fg = "foam" },
          DapUIStepBack = { fg = "foam" },
          DapUIStepOut = { fg = "foam" },
          DapUIStop = { fg = "love" },
          DapUIPlayPause = { fg = "pine" },
          DapUIRestart = { fg = "pine" },
          DapUIUnavailable = { fg = "muted" },
          IndentLineCurrent = { fg = "muted" },
          EasyDotnetTestRunnerSolution = { fg = "pine" },
          EasyDotnetTestRunnerProject = { fg = "rose" },
          EasyDotnetTestRunnerTest = { fg = "iris" },
          SnacksIndentScope = { fg = "overlay" },
          SnacksDashboardSpecial = { fg = "gold" },
          MiniIconsAzureBlend = { fg = "foam", bg = "foam", blend = 25 },
          MiniIconsBlueBlend = { fg = "pine", bg = "pine", blend = 25 },
          MiniIconsCyanBlend = { fg = "foam", bg = "foam", blend = 25 },
          MiniIconsGreenBlend = { fg = "leaf", bg = "leaf", blend = 25 },
          MiniIconsGreyBlend = { fg = "subtle", bg = "subtle", blend = 25 },
          MiniIconsOrangeBlend = { fg = "rose", bg = "rose", blend = 25 },
          MiniIconsPurpleBlend = { fg = "iris", bg = "iris", blend = 25 },
          MiniIconsRedBlend = { fg = "love", bg = "love", blend = 25 },
          MiniIconsYellowBlend = { fg = "gold", bg = "gold", blend = 25 },
        },
      }
      vim.cmd "colorscheme rose-pine"
    end,
  },
}
